namespace Sharpy.Unity.Editor
{
    // Usings are inside the namespace so BCL names (Path, List, Math, ...) win
    // over same-named Sharpy.* root types from the referenced Sharpy.Core.dll.
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Text;

    /// <summary>
    /// Decides whether Sharpy may write into, and delete from, the configured
    /// generated folder. The sync deletes every .cs in that folder that sharpyc
    /// did not produce, so the folder must be inside Assets/, hold no sources,
    /// and be Sharpy's: new or empty when first used, and marked from then on
    /// by a .gitignore whose first line is <see cref="MarkerLine"/> (dotfiles
    /// are not imported by Unity).
    /// </summary>
    internal static class SharpyGeneratedOwnership
    {
        internal const string MarkerLine = "# Generated by Sharpy; this folder is managed by com.antonsynd.sharpy";

        internal const string MarkerText = MarkerLine + "\n"
            + "# Every .cs file in it is replaced or deleted on compile; keep your own files elsewhere.\n"
            + "*\n";

        internal const string MarkerFileName = ".gitignore";

        // What generated C# always contains, and hand-written C# would not.
        private const string GeneratedSignature = "[global::Sharpy.SharpyModule(";

        /// <summary>
        /// Why <paramref name="generatedFolder"/> (as configured, relative to
        /// <paramref name="projectRoot"/>) cannot be the generated folder, or
        /// null. It must be a plain relative path to a folder strictly inside
        /// Assets/, compared as full paths, with no .spy source in it.
        /// </summary>
        internal static string CheckPath(string projectRoot, string generatedFolder, IEnumerable<string> spyAssets)
        {
            string configured = (generatedFolder ?? string.Empty).Trim();
            string invalid = $"Generated Output Path \"{configured}\" must be a folder of its own inside Assets/ "
                + "(e.g. Assets/SharpyGenerated). Nothing was generated or deleted.";

            string trimmed = configured.TrimEnd('/', '\\');

            if (trimmed.Length == 0 || Path.IsPathRooted(trimmed))
            {
                return invalid;
            }

            string[] segments = trimmed.Split('/', '\\');

            if (segments.Length < 2 || segments[0] != "Assets")
            {
                return invalid;
            }

            foreach (string segment in segments)
            {
                if (segment.Length == 0 || segment == "." || segment == ".." || segment.Trim().Length != segment.Length)
                {
                    return invalid;
                }
            }

            string assetsDir = Path.GetFullPath(Path.Combine(projectRoot, "Assets")).TrimEnd(Path.DirectorySeparatorChar)
                + Path.DirectorySeparatorChar;
            string folderAsset = string.Join("/", segments);
            string folderDir = Path.GetFullPath(Path.Combine(projectRoot, folderAsset)).TrimEnd(Path.DirectorySeparatorChar);

            if (!(folderDir + Path.DirectorySeparatorChar).StartsWith(assetsDir, StringComparison.OrdinalIgnoreCase)
                || folderDir.Length + 1 <= assetsDir.Length)
            {
                return invalid;
            }

            foreach (string spy in spyAssets)
            {
                if (spy.Replace('\\', '/').StartsWith(folderAsset + "/", StringComparison.OrdinalIgnoreCase))
                {
                    return $"Generated Output Path \"{configured}\" contains the source {spy}. It must be a folder "
                        + "of its own, since Sharpy replaces every .cs in it. Nothing was generated or deleted.";
                }
            }

            return null;
        }

        /// <summary>
        /// <see cref="CheckPath"/>, then <see cref="Claim"/> on the folder.
        /// Null when Sharpy may write to and delete from it.
        /// </summary>
        internal static string Prepare(string projectRoot, string generatedFolder, IEnumerable<string> spyAssets)
        {
            return CheckPath(projectRoot, generatedFolder, spyAssets)
                ?? Claim(FullPath(projectRoot, generatedFolder), SharpyProjectCompiler.NormalizeFolder(generatedFolder));
        }

        internal static string FullPath(string projectRoot, string generatedFolder)
        {
            return projectRoot + "/" + SharpyProjectCompiler.NormalizeFolder(generatedFolder);
        }

        /// <summary>
        /// Makes <paramref name="dir"/> Sharpy's, or says why it cannot. A
        /// missing or empty folder is created and marked. A marked folder is
        /// Sharpy's. A folder marked by an older version (a .gitignore of just
        /// "*") is adopted only if every .cs in it is generated C#. Anything
        /// else belongs to someone else and is left untouched.
        /// </summary>
        /// <param name="label">How the folder is named in the error; defaults to <paramref name="dir"/>.</param>
        internal static string Claim(string dir, string label = null)
        {
            string marker = Path.Combine(dir, MarkerFileName);

            if (IsMarked(marker))
            {
                return null;
            }

            if (!IsEmpty(dir) && !IsLegacyGenerated(dir, marker))
            {
                return $"{label ?? dir} already has files that Sharpy did not generate, so Sharpy will not write to it or "
                    + $"delete from it. Choose an empty folder as Generated Output Path, or, if the folder only holds "
                    + $"Sharpy output, delete it and recompile.";
            }

            Directory.CreateDirectory(dir);
            File.WriteAllText(marker, MarkerText, new UTF8Encoding(false));
            return null;
        }

        /// <summary>
        /// Empties a generated folder that is no longer the configured one: its
        /// generated scripts go (otherwise they compile next to the new
        /// folder's copies, CS0101), as do empty folders, and the folder itself
        /// when nothing but the marker is left. Does nothing to a folder that
        /// is not marked. Returns whether anything was deleted.
        /// </summary>
        internal static bool Retire(string dir)
        {
            if (!Directory.Exists(dir) || !IsOwned(dir))
            {
                return false;
            }

            bool changed = SharpyGeneratedSync.Sync(dir, new SharpyGeneratedFile[0]).Changed;
            string[] left = Directory.GetFileSystemEntries(dir);

            if (left.Length == 1 && Path.GetFileName(left[0]) == MarkerFileName)
            {
                File.Delete(left[0]);
                Directory.Delete(dir);

                string folderMeta = dir.TrimEnd('/', '\\') + ".meta";

                if (File.Exists(folderMeta))
                {
                    File.Delete(folderMeta);
                }

                changed = true;
            }

            return changed;
        }

        /// <summary>Whether <paramref name="dir"/> carries the marker.</summary>
        internal static bool IsOwned(string dir)
        {
            return IsMarked(Path.Combine(dir, MarkerFileName));
        }

        private static bool IsMarked(string marker)
        {
            if (!File.Exists(marker))
            {
                return false;
            }

            using (var reader = new StreamReader(marker))
            {
                string first = reader.ReadLine();
                return first != null && first.Trim() == MarkerLine;
            }
        }

        // macOS Finder's .DS_Store does not make a folder anyone's.
        private static bool IsEmpty(string dir)
        {
            if (!Directory.Exists(dir))
            {
                return true;
            }

            foreach (string entry in Directory.GetFileSystemEntries(dir))
            {
                if (Path.GetFileName(entry) != ".DS_Store")
                {
                    return false;
                }
            }

            return true;
        }

        private static bool IsLegacyGenerated(string dir, string marker)
        {
            if (!File.Exists(marker) || File.ReadAllText(marker).Trim() != "*")
            {
                return false;
            }

            foreach (string path in Directory.GetFiles(dir, "*.cs", SearchOption.AllDirectories))
            {
                if (File.ReadAllText(path).IndexOf(GeneratedSignature, StringComparison.Ordinal) < 0)
                {
                    return false;
                }
            }

            return true;
        }
    }
}
